### ISSUE TITLE
JointView fails for .hic files

### ISSUE THREAD

**Issue by tuomovirtanen** [GangCaoLab/CoolBox#56]
Jointview does not work for .hic files. The tracks are correct but hic matrix is only plotted from one region. Coolbox version 0.3.8

Here is the output for the mcool file
![image](https://user-images.githubusercontent.com/58848769/134148498-fb4cbc63-7721-4192-8158-78e2b3f8e10d.png)
![image](https://user-images.githubusercontent.com/58848769/134148435-9599bc5f-3f73-45c8-8946-6e82bc0d35b6.png)

Here is the output for .hic file
![image](https://user-images.githubusercontent.com/58848769/134148773-4638eae8-d793-40b0-8de3-e17ab47ad1bd.png)
![image](https://user-images.githubusercontent.com/58848769/134148845-c759362f-7520-44c1-be96-cccc8fe4115b.png)

**Comment by Nanguage** [comment]
Thanks for report bug, this has been fixed in 0.3.9.
![image](https://user-images.githubusercontent.com/14010939/149518609-0032b64f-bca9-4e44-9afe-5d8b4f90eb3f.png)
![image](https://user-images.githubusercontent.com/14010939/149518650-3afbc375-ca64-4bd6-bccf-3d351b7e55ae.png)

You can update from the source to use this fix:

```bash
$ git clone --depth=1 https://github.com/GangCaoLab/CoolBox.git
$ cd Coolbox
$ pip install .
```
