### ISSUE TITLE
feature request: plot on given axes

### ISSUE THREAD

**Issue by jksr** [GangCaoLab/CoolBox#6]
is it possible to plot the frame in a user defined matplotlib axes?

**Comment by Nanguage** [comment]
It's hard to implement this, because the frame is represent as a fig object, you can plot track on axes, but figure can not. But you can compose the frame using svg_utils, just like we do in the [jointview](https://github.com/GangCaoLab/CoolBox/blob/master/coolbox/core/frame/superframe/jointview.py).
It can achieve this effect: https://gangcaolab.github.io/CoolBox/_gallery/joint_view.html .

I hope it's helpful.
